/*
 * Generated by dtrace(1M).
 */

#ifndef	_SKELETON_PROBES_H
#define	_SKELETON_PROBES_H



#ifdef	__cplusplus
extern "C" {
#endif

#if _DTRACE_VERSION

#define	SKELETON_CLOSE() \
	__dtrace_skeleton___close()
#define	SKELETON_CLOSE_ENABLED() \
	__dtraceenabled_skeleton___close()
#define	SKELETON_OPEN() \
	__dtrace_skeleton___open()
#define	SKELETON_OPEN_ENABLED() \
	__dtraceenabled_skeleton___open()


extern void __dtrace_skeleton___close(void);
extern int __dtraceenabled_skeleton___close(void);
extern void __dtrace_skeleton___open(void);
extern int __dtraceenabled_skeleton___open(void);

#else

#define	SKELETON_CLOSE()
#define	SKELETON_CLOSE_ENABLED() (0)
#define	SKELETON_OPEN()
#define	SKELETON_OPEN_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _SKELETON_PROBES_H */
